[profile.default]
src = '.'
test = '.'
out = 'out'
libs = ['../../../lib']

remappings = [
    'target=/home/giovanni/tirocinio/contracts-verification-benchmark/contracts/bank/versions/',
    'forge-std=/home/giovanni/tirocinio/contracts-verification-benchmark/lib/forge-std/src/'
]