[profile.default]
src = '.'
test = '.'
out = 'out'
libs = ['lib']
skip = ['lib/**']

remappings = [
    'target/=versions/',
    'lib/=lib/',
    'halmos-cheatcodes/=lib/halmos-cheatcodes/src/',
    'forge-std/=lib/forge-std/src/'
]

[lint]
lint_on_build = false
