[profile.default]
src = '.'
test = '.'
out = 'out'

remappings = [
    'forge-std/=/home/giovanni/tirocinio/contracts-verification-benchmark/lib/forge-std/src/',
    'target/=/home/giovanni/tirocinio/contracts-verification-benchmark/regression/assembly_assignment/'
]